from typing import TypeAlias

_TimeTuple: TypeAlias = tuple[int, int, int, int, int, int, int, int]

def gmtime(secs: int | None = None, /) -> _TimeTuple: ...
def localtime(secs: int | None = None, /) -> _TimeTuple: ...
def mktime(date_time: _TimeTuple, /) -> int: ...
def sleep_ms(ms: int, /) -> None: ...
def ticks_add(ticks: int, delta: int, /) -> int: ...
def ticks_diff(ticks1: int, ticks2: int, /) -> int: ...
def ticks_ms() -> int: ...
